config/routes.rb
Rails.application.routes.draw do
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/polls/info' => 'polls#info'

  resources :votes, only: [:create]
  resources :users, only: [:show]
  resources :polls
  root to: 'polls#index'

end

app/models/idol_list.rb
class IdolList < ActiveRecord::Base

end

app/models/ip.rb
class Ip < ActiveRecord::Base
  belongs_to :user
end

app/models/poll.rb
# == Schema Information
#
# Table name: polls
#
#  id         :integer          not null, primary key
#  topic      :text
#  created_at :datetime
#  updated_at :datetime
#

class Poll < ActiveRecord::Base
  has_many :vote_options, dependent: :destroy

  accepts_nested_attributes_for :vote_options, :reject_if => :all_blank, :allow_destroy => true

  validates :topic, presence: true

  def normalized_votes_for(option)
    votes_summary == 0 ? 0 : (option.votes.count.to_f / votes_summary) * 100
  end

  def votes_summary
    vote_options.inject(0) {|summary, option| summary + option.votes.count}
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  image_url  :string(255)
#  uid        :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class User < ActiveRecord::Base
  has_many :votes, dependent: :destroy
  has_many :vote_options, through: :votes

  def voted_for?(poll)
    votes.any? {|v| v.vote_option.poll == poll}
  end

  has_secure_password
end

app/models/user_setting.rb
class UserSetting < ActiveRecord::Base
  belongs_to :user
end

app/models/vote.rb
# == Schema Information
#
# Table name: votes
#
#  id             :integer          not null, primary key
#  user_id        :integer
#  vote_option_id :integer
#  created_at     :datetime
#  updated_at     :datetime
#

class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :vote_option

  counter_culture :vote_option
end

app/models/vote_option.rb
# == Schema Information
#
# Table name: vote_options
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  poll_id     :integer
#  created_at  :datetime
#  updated_at  :datetime
#  votes_count :integer          default(0), not null
#

class VoteOption < ActiveRecord::Base
  belongs_to :poll
  has_many :votes, dependent: :destroy
  has_many :users, through: :votes
  mount_uploader :image, ImageUploader

  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end


end

app/controllers/idol_controller.rb
class IdolController < ApplicationController
  def create
    if current_user && params[:poll] && params[:poll][:id] && params[:vote_option] && params[:vote_option][:id]
      @poll = Poll.find_by_id(params[:poll][:id])
      @option = @poll.vote_options.find_by_id(params[:vote_option][:id])
      if @option && @poll && !current_user.voted_for?(@poll)
        current_user.votes.create({vote_option_id: @option.id})
      else
        render js: 'alert(\'이미 투표가 되어있어 저장이 되지 않습니다.\');'
      end
    else
      render js: 'alert(\'투표가 저장되지 않았습니다.\');'
    end
  end

  def info
  end
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :authorize
  def index
    @polls = Poll.order('created_at DESC')
    @user_setting = UserSetting.find_by_user_id(current_user)
  end

  def info
    @user = User.order('created_at DESC')
    @remote_ip = request.remote_ip.split('.')[0]
    @idols = IdolList.order('created_at DESC')
  end

  def show
    @poll = Poll.includes(:vote_options).find_by_id(params[:id])
    @vote = Vote.new
    @user_setting = UserSetting.find_by_user_id(current_user)
    #@idol = IdolList.where(name: option.title).take.image
  end

  def new
    @poll = Poll.new
  end

  def edit
    @poll = Poll.find_by_id(params[:id])
  end

  def update
    @poll = Poll.find_by_id(params[:id])
    if @poll.update_attributes(poll_params)
      flash[:success] = '투표가 업데이트되었습니다!'
      redirect_to polls_path
    else
      render 'edit'
    end
  end

  def create
    @poll = Poll.new(poll_params)
    if @poll.save
      flash[:success] = '투표가 새로 만들어졌습니다!'
      redirect_to polls_path
    else
      render 'new'
    end
  end

  def destroy
    @poll = Poll.find_by_id(params[:id])
    if @poll.destroy
      flash[:success] = '투표가 삭제되었습니다!'
    else
      flash[:warning] = '투표를 삭제하는 과정에서 오류가 생겼습니다....'
    end
    redirect_to polls_path
  end

  private

  def poll_params
    params.require(:poll).permit(:topic, :close_time, vote_options_attributes: [:id, :title, :image, :_destroy])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_name(params[:name])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end
end

app/controllers/users_controller.rb
require 'open-uri'
require 'nokogiri'
require 'uri'
require 'iconv'
require 'cgi'

class UsersController < ApplicationController

  def show
    @user = User.includes(:vote_options).find_by_id(params[:id])
  end

  def new
  end

  def change
    user = User.where(name: user_params[:name]).take
  end

  def create
    user = User.new(user_params)
    name = user_params[:name]

    conv = Iconv.new('EUC-KR','UTF-8')
    query = conv.iconv(name)
    de_name = CGI::escape(query)

    #이름을 주소에 적용해 웃대에 답글 검색을 한다.
    one = Nokogiri::HTML(open("http://web.humoruniv.com/board/humor/comment_search.html?sort=mtime&searchday=all&sk=#{de_name}"))
    #아이콘을 찾아 그 안의 아이콘 위치 주소를 얻는다.
    #hu_icon = one.xpath("//img[@class='hu_icon']")[0]["src"]
    hu_icon = one.xpath("//img[@class='hu_icon']")[0]



    if !hu_icon.nil? && User.where(name: name).take.nil?
      if user.save
        session[:user_id] = user.id

        setting = UserSetting.new
        setting.user = user
        setting.ip = request.remote_ip
        setting.is_admin = false
        if (UserSetting.where(ip: request.remote_ip).take.nil?)
          setting.is_ban = false
        else
          setting.is_ban = true
        end

        setting.save

        redirect_to '/'
      else
        redirect_to '/signup'
      end
    else
      redirect_to '/signup'
    end

  end

  private

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end

end

app/controllers/votes_controller.rb
require 'date'
class VotesController < ApplicationController
  def create
    if current_user && params[:poll] && params[:poll][:id] && params[:vote_option] && params[:vote_option][:id]
      Time.zone = 'Seoul'
      @poll = Poll.find_by_id(params[:poll][:id])
      @option = @poll.vote_options.find_by_id(params[:vote_option][:id])
      @option.save
      if ((Time.zone.now.to_time - @poll.close_time.to_time)).to_f <= 0
        if @option && @poll && !current_user.voted_for?(@poll)
          current_user.votes.create({ vote_option_id: @option.id })
        else
          render js: 'alert(\'이미 투표가 되어있어 저장이 되지 않습니다.\');'
        end
      else
        render js: 'alert(\'투표 시간이 초과되었습니다.\');'
      end
    else
      render js: 'alert(\'투표가 저장되지 않았습니다.\');'
    end
  end

  def info
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/idol_helper.rb
module IdolHelper
end

app/helpers/polls_helper.rb
module PollsHelper

  def visualize_votes_for(option)
    content_tag :div, class: 'progress' do
      content_tag :div, class: 'progress-bar',
                  style: "width: #{option.poll.normalized_votes_for(option)}%" do
        "#{option.votes.count}"
      end
    end
  end

end
=begin

=end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>만게 투표</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'countdown' %>
  <%= csrf_meta_tags %>

</head>
<body>

<div class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container">
    <div class="navbar-brand">
        <%= link_to '만게 투표', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="navbar-nav mr-auto">
        <% if current_user %>
          <% if UserSetting.find_by_user_id(current_user).is_admin %>
            <li><%= link_to '투표 추가', new_poll_path, class: "nav-item nav-link" %></li>
            <li><%= link_to '투표 이력', '/polls/info', class: "nav-item nav-link" %></li>
          <% end %>
        <% end %>
      </ul>
      <ul class="navbar-nav ml-auto">
        <% if current_user %>
          <li><%= link_to current_user.name, user_path(current_user), class: "nav-item nav-link" %></li>
          <li><%= link_to '로그아웃', '/logout', class: "nav-item nav-link" %></li>
        <% else %>
          <li><%= link_to '로그인', '/login', class: "nav-item nav-link" %></li>
          <li><%= link_to '회원등록', '/signup', class: "nav-item nav-link" %></li>
        <% end %>
      </ul>
    </div>

  </div>
</div>

<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
  <% end %>

  <div class="page-header">
    <h1><%= yield :page_header %></h1>
  </div>

  <%= yield %>
</div>


<div id="footer">

    <p class="text-muted">Created by 이즈미남편</p>
  </div>
</div>

</body>
</html>

app/views/polls/_form.html.erb
<%= form_for @poll do |f| %>
  <%= render 'shared/errors', object: @poll %>

  <div class="form-group">
    <%= f.label :topic, "투표 주제" %>
    <%= f.text_area :topic, rows: 3, required: true, class: 'form-control' %>
    <br/>
    <%= f.label :close_time, "종료 시간" %>
    <%= f.datetime_select(:close_time, :ampm => true, default: 15.minutes.from_now) %>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">옵션</div>
    <div class="panel-body">
      <%= f.fields_for :vote_options do |options_form| %>
        <%= render 'vote_option_fields', f: options_form %>
      <% end %>

      <div class="links">
        <%= link_to_add_association '옵션 추가', f, :vote_options %>
      </div>
    </div>
  </div>

  <%= f.submit '생성하기', class: 'btn btn-primary btn-lg' %>
<% end %>

app/views/polls/_vote_option.html.erb
  <div class="form-group">
    <%= content_tag(:label) do %>
      <% unless current_user.voted_for?(@poll) %>
        <%= image_tag(option.image, height: '48', width: '48') %>
        <%= radio_button_tag 'vote_option[id]', option.id, class: "form-check" %>
      <% end %>
      <%= option.title %>
    <% end %>
    <% if current_user.voted_for?(@poll) %>
    <%= visualize_votes_for option %>
    <% end %>
  </div>

app/views/polls/_vote_option_fields.html.erb
<div class="nested-fields">
  <div class="form-group">
    <%= f.label :title, "항목" %>
    <%= f.text_field :title, class: 'form-control', required: true %>
    <%= f.file_field :image %>
  </div>
  <%= link_to_remove_association "옵션 제거", f %>
</div>

app/views/polls/_voting_form.html.erb
  <%= form_tag votes_path, method: :post, remote: true, id: 'voting_form' do %>
    <%= hidden_field_tag 'poll[id]', @poll.id %>
    <%= render partial: 'polls/vote_option', collection: @poll.vote_options, as: :option %>

    <p><b>총 투표 수 : <%= @poll.votes_summary %></b></p>
    <p><b>제한 시간 : <%= @poll.close_time.strftime("%m월 %d일 %H시 %M분 까지") %></b></p>

    <% if current_user.voted_for?(@poll) %>
      <p>이미 투표에 참여했습니다!</p>
    <% else %>
      <%= submit_tag '투표', class: 'btn btn-lg btn-primary' %>
    <% end %>
  <% end %>

app/views/polls/edit.html.erb
<% content_for(:page_header) {"투표 수정"} %>

<%= render 'form' %>

app/views/polls/index.html.erb
<div class="jumbotron">
  <h1 class="display-3">만게 투표</h1>
  <p class="lead"><strong>진행 중인 이벤트 : </strong><span style = "color: #007bff"> 테스트 중 </span></p>
</div>


<% @polls.each do |poll| %>
  <div class="card">
    <div class="card-body">
      <h4 class="card-title"><%= poll.topic %> <span class="badge badge-pill badge-primary">투표 수: <%= poll.votes_summary %></span></h4>

      <p>
        <% if current_user && !@user_setting.is_ban %>
          <%= link_to '참여!', poll_path(poll), class: 'btn btn-primary' %>
        <% elsif current_user && @user_setting.is_ban %>
          당신은 중복 계정 생성이 의심되어 밴 처리가 되었습니다. 자세한 사항은 '이즈미남편'에게 쪽지로 문의하세요.
        <% else %>
          <%= link_to '여기', '/login' %>에 로그인을 하시거나, 회원등록이 되어있지 않으시다면 <%= link_to '여기', '/signup' %>에서 회원등록을 하세요.
        <% end %>
      </p>

      <% if current_user %>
        <% if @user_setting.is_admin %>
          <%= link_to '수정', edit_poll_path(poll), class: 'card-link' %>
          <%= link_to '삭제', poll_path(poll),
                      method: :delete,
                      class: 'card-link', style: "color: red", data: {confirm: '정말로 제거하겠습니까?'} %>
        <% end %>
      <% end %>
    </div>

  </div>
<% end %>

<div style="margin-top: 100px;">
  <% if current_user %>
    <%= link_to "<" + current_user.name + ">으로 로그인되었습니다.", user_path(current_user), class: "btn btn-primary btn-lg btn-block" , id: "muser"%>
  <% else %>
    <a href="/login" class="btn btn-primary btn-lg btn-block" id = "mlogin" role="button" aria-pressed="true">(모바일 전용)로그인</a>
  <% end %>
</div>

app/views/polls/info.html.erb
<% content_for(:page_header) {"투표 이력"} %>
<p>[테스트용] 현재 접속 ip = <%= @remote_ip %></p>
<% @user.each do |u| %>
<h3><%= u.name %></h3>
<% u.vote_options.each do |option| %>
<p><%= option.poll.topic %></p>
<% end %>
<% end %>

app/views/polls/new.html.erb
<% content_for(:page_header) {"투표 새로 만들기"} %>

<%= render 'form' %>

app/views/polls/show.html.erb
<div class="card">
  <h4 class="card-header"><%= @poll.topic%></h4>
  <div class="card-body">
    <% if @user_setting.is_ban %>
      <h3>당신은 중복 계정 생성이 의심되어 밴 처리가 되었습니다.</h3>
      밴이 되신 회원은 투표에 참여하실 수 없습니다.<br>
      자세한 사항은 '이즈미남편'에게 쪽지로 문의하세요.
    <% else %>
      <%= render 'voting_form' %>
    <% end %>
  </div>


</div>



<script data-turbolinks-track="true">
  $(document).ready(function() {
    var voting_form = $('#voting_form');
    voting_form.validate({
      focusInvalid: false,
      errorClass: 'alert alert-warning',
      errorElement: "div",
      errorPlacement: function(error, element) { voting_form.before(error); },
      rules: {
        'vote_option[id]': {
          required: true
        }
      },
      messages: {
        'vote_option[id]': {
          required: "하나만 선택하세요."
        }
      }
    });
  });
</script>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="alert alert-warning">
    <h4>The following errors were found:</h4>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<% content_for(:page_header) {"회원 등록"} %>

<%= bootstrap_form_for :user, url: '/users' do |f| %>
    <%= f.label :name, '웃대닉네임' %>
    <%= f.text_field :name, hide_label: true %>
    <h6>웃대 닉네임 인증은 웃대에 댓글을 단 것으로 인증하는 방식입니다.</h6>
    <h6>정확한 웃대 닉네임을 작성하지 않으시면 회원등록이 되지 않으니 이 점 참고하시기 바랍니다.</h6>
    <h5 style="color: red;">주의 : ip 검사를 통해 부계정 사용이 발견될 시 투표 박탈, 회원등록 불가능하게 하겠습니다.</h5>
    <%= f.label :password, '비밀번호' %>
    <%= f.password_field :password, hide_label: true %>
    <%= f.label :password_confirmation, '비밀번호 재확인' %>
    <%= f.password_field :password_confirmation, hide_label: true %>
    <%= f.submit "회원등록" %>
<% end %>

app/views/users/show.html.erb
<% content_for(:page_header) do %>
  <%= "#{@user.name}의 프로필" %>
<% end %>

<h2>투표에 참여한 이력</h2>

<% @user.vote_options.each do |option| %>
  <div class="panel panel-default">
    <div class="panel-heading"><%= link_to option.poll.topic, poll_path(option.poll) %></div>
    <div class="panel-body">
      <%= option.title %>
    </div>
  </div>
<% end %>

app/views/votes/create.js.erb
$('#voting_form').replaceWith('<%= j render 'polls/voting_form' %>');